Output create_key.gif
Require ssh-man
Set Shell bash
Set FontSize 12
Set Theme "Atom"
Set WindowBar Colorful
Set Framerate 60
Set Width 1200
Set Height 1000

Set PlaybackSpeed 0.75
Set TypingSpeed 120ms

Sleep 1s
Type "ssh-man"
Enter
Sleep 1s
Type "g"
Sleep 1s
Down
Sleep 50ms
Down
Sleep 50ms
Enter
Sleep 900ms
Tab
Sleep 200ms
Tab
Sleep 200ms
Tab
Sleep 500ms
Left
Sleep 500ms
Enter
Sleep 2.5s
Enter
Sleep 700ms
Type "e"
Sleep 2s
Escape
Sleep 2.5s
Ctrl+C
Sleep 500ms

