Output rotate_key.gif
Require ssh-man
Set Shell bash
Set FontSize 12
Set Theme "Atom"
Set WindowBar Colorful
Set Framerate 60
Set Width 1200
Set Height 1000

Set PlaybackSpeed 0.5
Set TypingSpeed 100ms

Type "ssh-man"
Sleep 50ms
Enter
Sleep 250ms
Type "r"
Sleep 550ms
Enter
Sleep 250ms
Down
Sleep 250ms
Down
Sleep 250ms
Enter
Tab@275ms 1
Tab@275ms 1
Left
Sleep 250ms
Enter
Sleep 500ms
Enter
Sleep 500ms
Enter
Sleep 550ms
Enter
Sleep 750ms
Ctrl+c